name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  golang:
    name: Golang
    permissions:
      contents: write
      pull-requests: write
      checks: write
    uses: depado/github-actions/.github/workflows/golang.yml@main
    with:
      build-command: make build-noproto

  docker:
    name: Docker
    needs: [golang]
    permissions:
      contents: read
      packages: write
      actions: read
    uses: depado/github-actions/.github/workflows/docker.yml@main
    secrets:
      cleanup-token: ${{ secrets.PAT_DELETE_PACKAGES }}

  docker-packed:
    name: Docker Packed
    needs: [golang]
    permissions:
      contents: read
      packages: write
      actions: read
    uses: depado/github-actions/.github/workflows/docker.yml@main
    with:
      dockerfile: "./Dockerfile.pack"
      tag-suffix: "-packed"
      tag-latest: false
    secrets:
      cleanup-token: ${{ secrets.PAT_DELETE_PACKAGES }}

